# Generated by Django 5.2.16 on 2026-07-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_upload_export', 'Can upload a raw clinic data export')],
                'default_permissions': [],
            },
        ),
    ]
