# Generated by Django 5.2.16 on 2026-07-20 08:06

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text="Founders' welcome / message (PDF p.5).")),
                ('vision', wagtail.fields.RichTextField(blank=True, help_text='Vision statement (PDF p.6).')),
                ('mission', wagtail.fields.RichTextField(blank=True, help_text='Mission statement (PDF p.6).')),
                ('objectives', wagtail.fields.RichTextField(blank=True, help_text='Objectives (PDF p.6).')),
                ('quality_of_care', wagtail.fields.RichTextField(blank=True, help_text='Quality-of-care model (PDF p.7).')),
                ('founding_story', wagtail.fields.RichTextField(blank=True, help_text='Inauguration & first medical camp (PDF p.11–13).')),
            ],
            options={
                'verbose_name': 'About page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Optional lead text above the details.')),
            ],
            options={
                'verbose_name': 'Contact page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OurWorkPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text="Introduction to the clinic's work.")),
                ('infrastructure', wagtail.fields.RichTextField(blank=True, help_text='Our infrastructure (PDF p.16–17).')),
            ],
            options={
                'verbose_name': 'Our Work page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Team introduction ("united by a shared commitment…", PDF p.10).')),
            ],
            options={
                'verbose_name': 'Team page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 10), ('impact_stats', 15), ('donate_cta', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 140, 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Urdu tagline, rendered right-to-left.', 'max_length': 80, 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Shown in the placeholder until a real image is chosen.', 'max_length': 80, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 16, 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('headline', 1), ('intro', 2), ('primary_cta_label', 3), ('primary_cta_page', 4), ('secondary_cta_label', 3), ('secondary_cta_page', 4), ('tagline', 5), ('image', 6), ('media_caption', 7), ('stat_value', 8), ('stat_label', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'The figure, formatted exactly as it should show, e.g. "36k+".', 'max_length': 16}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Short caption under the figure.', 'max_length': 80}), 13: ('wagtail.blocks.StructBlock', [[('value', 11), ('label', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('caption', 1), ('stats', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 17: ('wagtail.blocks.URLBlock', (), {'help_text': 'External link, used only if no internal page is chosen.', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('heading', 16), ('body', 2), ('cta_label', 3), ('cta_page', 4), ('cta_url', 17), ('note', 16)]], {})}, help_text='Compose the home page from the section kit.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional short lead text (legacy Plan 01 field; the body below drives the page).'),
        ),
        migrations.CreateModel(
            name='ContactBankSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('map_embed_url', models.URLField(blank=True, help_text='Optional map embed URL (e.g. an OpenStreetMap share link).')),
                ('bank_account_title', models.CharField(blank=True, max_length=140)),
                ('bank_name', models.CharField(blank=True, max_length=140)),
                ('bank_iban', models.CharField(blank=True, max_length=60)),
                ('bank_account_number', models.CharField(blank=True, max_length=60)),
                ('bank_branch', models.CharField(blank=True, help_text='Branch name and/or code.', max_length=140)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Contact & bank details',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('planned', 'Planned')], default='active', help_text='"Planned" shows a coming-soon tag and must not read as available.', max_length=20)),
                ('image', models.ForeignKey(blank=True, help_text='Optional icon or photo for the service card.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.ourworkpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(help_text='e.g. "Instagram".', max_length=60)),
                ('url', models.URLField()),
                ('setting', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.contactbanksettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=140)),
                ('category', models.CharField(choices=[('doctors', 'Doctors'), ('staff', 'Staff & Committee')], default='doctors', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Short one- or two-line bio.')),
                ('photo', models.ForeignKey(blank=True, help_text='Portrait; falls back to a placeholder until one is added.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.teampage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
