# Generated by Django 5.2.16 on 2026-07-21 16:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_homepage_body"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonatePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text='"Giving with Purpose" message (PDF p.18).',
                    ),
                ),
                (
                    "zakat_description",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Zakat section: specific eligibility/calculation rules (PDF p.18).",
                    ),
                ),
                (
                    "sadaqa_description",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Sadaqa section: general voluntary giving (PDF p.18).",
                    ),
                ),
                (
                    "how_to_give",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="How-to-give steps for the bank transfer below.",
                    ),
                ),
                (
                    "in_kind_giving",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="In-kind options (medicine, equipment, volunteering) — arranged via Contact, not a form.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donate page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
