# Generated by Django 5.2.16 on 2026-07-21 18:14

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_donatepage'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampReportIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Optional intro copy for the archive.')),
            ],
            options={
                'verbose_name': 'Camp report index page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CampReportPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('camp_date', models.DateField(help_text='The date of the camp.')),
                ('location', models.CharField(blank=True, max_length=180)),
                ('patients_children', models.PositiveIntegerField(default=0, help_text='Patients served — Paediatrics / children.')),
                ('patients_general', models.PositiveIntegerField(default=0, help_text='Patients served — General Medicine / adults.')),
                ('patients_welfare', models.PositiveIntegerField(default=0, help_text='Patients served under the Welfare (free-of-cost) category.')),
                ('services_offered', wagtail.fields.StreamField([('service', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120})}, help_text='Services offered at this camp, one entry each.')),
                ('partner_credits', models.TextField(blank=True, help_text='Partner organisations and volunteers, one per line.')),
                ('narrative', wagtail.fields.RichTextField(blank=True, help_text="The camp's story.")),
                ('photos', wagtail.fields.StreamField([('photo', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Describe the image for screen-reader users. Falls back to the image's own title if left blank.", 'max_length': 180, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Tick to confirm every identifiable person in this photo has consented to it being published (brand-guidelines.md §5).', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('alt_text', 1), ('caption', 2), ('consent_confirmed', 3)]], {})}, help_text='Camp photos — consent required before publish.')),
            ],
            options={
                'verbose_name': 'Camp report',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Optional intro copy above the grid.')),
            ],
            options={
                'verbose_name': 'Gallery page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsletterIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Optional intro copy for the archive.')),
            ],
            options={
                'verbose_name': 'Newsletter index page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsletterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('issue_date', models.DateField(help_text="The issue's cover date.")),
                ('summary', models.TextField(blank=True, help_text="Short teaser blurb — shown in the archive list and Home's latest-newsletter section.")),
                ('body', wagtail.fields.StreamField([('paragraph', 0), ('photo', 5)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "Describe the image for screen-reader users. Falls back to the image's own title if left blank.", 'max_length': 180, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Tick to confirm every identifiable person in this photo has consented to it being published (brand-guidelines.md §5).', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 1), ('alt_text', 2), ('caption', 3), ('consent_confirmed', 4)]], {})}, help_text="The issue's content.")),
            ],
            options={
                'verbose_name': 'Newsletter',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('alt_text', models.CharField(blank=True, help_text="Describe the image for screen-reader users. Falls back to the image's own title if left blank.", max_length=180)),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('consent_confirmed', models.BooleanField(default=False, help_text='Tick to confirm every identifiable person in this photo has consented to it being published (brand-guidelines.md §5).')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.gallerypage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
