# Generated by Django 5.2.16 on 2026-07-22 23:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_campreportindexpage_campreportpage_gallerypage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 11), ('impact_stats', 16), ('circle_of_care', 23), ('donate_cta', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 140, 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Style the primary CTA as the amber Zakat/Sadaqa donate button (brand-guidelines.md §7). Leave off for any other link — amber is Donate-only.', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Urdu tagline, rendered right-to-left.', 'max_length': 80, 'required': False}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Shown in the placeholder until a real image is chosen.', 'max_length': 80, 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 16, 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('headline', 1), ('intro', 2), ('primary_cta_label', 3), ('primary_cta_page', 4), ('primary_cta_donate', 5), ('secondary_cta_label', 3), ('secondary_cta_page', 4), ('tagline', 6), ('image', 7), ('media_caption', 8), ('stat_value', 9), ('stat_label', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'The figure, formatted exactly as it should show, e.g. "36k+".', 'max_length': 16}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Short caption under the figure.', 'max_length': 80}), 14: ('wagtail.blocks.StructBlock', [[('value', 12), ('label', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('caption', 1), ('stats', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Defaults to "Quality of Care" if left blank.', 'max_length': 120, 'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'Full stage name, shown in the hub.', 'max_length': 80}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': "On-ring label — keep brief so it fits the wedge (the longest example, 'Doctor's Consultation', is 21 characters).", 'max_length': 28}), 20: ('wagtail.blocks.TextBlock', (), {'help_text': 'Detail shown in the hub when this stage is selected.'}), 21: ('wagtail.blocks.StructBlock', [[('name', 18), ('short', 19), ('desc', 20)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {}), 23: ('wagtail.blocks.StructBlock', [[('heading', 17), ('stages', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 25: ('wagtail.blocks.URLBlock', (), {'help_text': 'External link, used only if no internal page is chosen.', 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('heading', 24), ('body', 2), ('cta_label', 3), ('cta_page', 4), ('cta_url', 25), ('note', 24)]], {})}, help_text='Compose the home page from the section kit.'),
        ),
    ]
