# Generated by Django 5.2.16 on 2026-07-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='category',
            field=models.CharField(choices=[('doctors', 'Volunteers'), ('staff', 'Staff & Committee')], default='doctors', max_length=20),
        ),
    ]
