# Generated by Django 5.2.16 on 2026-07-23 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_teammember_category'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campreportpage',
            name='partner_credits',
        ),
        migrations.RemoveField(
            model_name='campreportpage',
            name='patients_children',
        ),
        migrations.RemoveField(
            model_name='campreportpage',
            name='patients_general',
        ),
        migrations.RemoveField(
            model_name='campreportpage',
            name='patients_welfare',
        ),
        migrations.RemoveField(
            model_name='campreportpage',
            name='services_offered',
        ),
        migrations.AddField(
            model_name='campreportpage',
            name='report_document',
            field=models.ForeignKey(blank=True, help_text='Optional source report PDF to offer as a download.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
