# Generated by Django 5.2.16 on 2026-07-23 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_campreportpage_partner_credits_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='report_teaser_image',
            field=models.ForeignKey(blank=True, help_text="Illustrative photo for the 'Latest daily report' teaser below the section kit — not tied to any specific report (those auto-publish daily with no admin step of their own), so this is a generic clinic/camp photo the admin curates by hand. Falls back to the shared placeholder until set.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
