# Generated by Django 5.2.16 on 2026-07-23 19:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_homepage_report_teaser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='photos',
            field=wagtail.fields.StreamField([('photo', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Describe the image for screen-reader users. Falls back to the image's own title if left blank.", 'max_length': 180, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Tick to confirm every identifiable person in this photo has consented to it being published (brand-guidelines.md §5).', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('alt_text', 1), ('caption', 2), ('consent_confirmed', 3)]], {})}, help_text="Patient-care and group/community photos illustrating the clinic's story — each still requires consent to be ticked before it can be saved (brand-guidelines.md §5)."),
        ),
    ]
