# Generated by Django 5.2.16 on 2026-07-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aboutpage_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='zakat_avg_spend',
            field=models.CharField(blank=True, help_text='Third figure in the live \'Our impact so far\' band: average spend per Zakat-funded visit, formatted exactly as it should show (e.g. "PKR 180/visit"). Hand-typed and hand-updated — the pipeline never ingests fee/expenditure data (Plan 11 Track F3), so unlike the other two figures in the band this one can\'t be computed live. Left blank, the band shows only the two live stats.', max_length=16),
        ),
    ]
