# Generated by Django 5.2.16 on 2026-07-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='zakat_avg_spend',
            field=models.CharField(blank=True, help_text='Third figure in the live \'Our impact so far\' band: average spend per Zakat-funded visit, as a bare number only (e.g. "180", not "PKR 180/visit") — the band renders "PKR" as a fixed prefix and the per-visit meaning is in the figure\'s label, not typed here (Plan 11 D13 redesign — a hand-typed currency string used to break the band\'s number-baseline alignment). Hand-typed and hand-updated — the pipeline never ingests fee/expenditure data (Plan 11 Track F3), so unlike the other two figures in the band this one can\'t be computed live. Left blank, the band shows only the two live stats.', max_length=16),
        ),
    ]
