# Generated by Django 5.2.16 on 2026-07-24 12:41

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_homepage_zakat_avg_spend'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterpage',
            name='issue_label',
            field=models.CharField(blank=True, help_text='Optional, shown after the issue date in the masthead, e.g. "Inaugural Issue".', max_length=60),
        ),
        migrations.AlterField(
            model_name='newsletterpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('photo', 5), ('stat_band', 12), ('highlights', 16), ('feature_split', 23)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "Describe the image for screen-reader users. Falls back to the image's own title if left blank.", 'max_length': 180, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Tick to confirm every identifiable person in this photo has consented to it being published (brand-guidelines.md §5).', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 1), ('alt_text', 2), ('caption', 3), ('consent_confirmed', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Our impact, at a glance', 'max_length': 120}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. "May–June 2026"', 'max_length': 60, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. "763" or "64%"', 'max_length': 16}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 90}), 10: ('wagtail.blocks.StructBlock', [[('value', 8), ('label', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'max_num': 3}), 12: ('wagtail.blocks.StructBlock', [[('heading', 6), ('updated', 7), ('stats', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'Highlights this issue', 'max_length': 90}), 14: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold'], 'help_text': 'Keep it to a sentence; bold the lead phrase.'}), 15: ('wagtail.blocks.ListBlock', (14,), {'max_num': 6}), 16: ('wagtail.blocks.StructBlock', [[('heading', 13), ('items', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional, e.g. "In focus" — set on the first split only if wanted.', 'max_length': 60, 'required': False}), 18: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 19: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Show the photo on the right instead of the left.', 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'max_length': 16}), 21: ('wagtail.blocks.StructBlock', [[('value', 20), ('label', 9)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {'max_num': 2}), 23: ('wagtail.blocks.StructBlock', [[('eyebrow', 17), ('heading', 9), ('text', 18), ('photo', 5), ('reverse', 19), ('pull_stats', 22)]], {})}, help_text="The issue's content."),
        ),
        migrations.AlterField(
            model_name='newsletterpage',
            name='summary',
            field=models.TextField(blank=True, help_text="Short teaser blurb — shown in the archive list, the masthead lede, and Home's latest-newsletter section."),
        ),
    ]
