# Generated by Django 5.2.16 on 2026-07-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_newsletterpage_issue_label_alter_newsletterpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactbanksettings",
            name="map_embed_url",
            field=models.URLField(
                blank=True,
                help_text="Optional map embed URL — the iframe src from Google Maps → Share → Embed a map. A share link (maps.app.goo.gl/…) will not render.",
                max_length=600,
            ),
        ),
    ]
