# Generated by Django 5.2.16 on 2026-07-29 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_contactbanksettings_map_embed_url'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, help_text='Optional, ~140 characters of guidance from the design handoff (field allows a little headroom).', max_length=160)),
                ('link_url', models.URLField(blank=True, help_text="Optional. Mutually exclusive with 'flyer' in the home-page card — set one or the other, not both (if both are set, the flyer takes precedence).")),
                ('flyer', models.ForeignKey(blank=True, help_text="Optional. When set, the home-page card opens this image in the site's shared lightbox instead of linking to 'link_url'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Upcoming event',
                'ordering': ['date'],
            },
        ),
    ]
