# Generated by Django 5.2.16 on 2026-07-21 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_date', models.DateField(db_index=True, unique=True)),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('male_patients', models.PositiveIntegerField(default=0)),
                ('female_patients', models.PositiveIntegerField(default=0)),
                ('other_or_unknown_sex_patients', models.PositiveIntegerField(default=0)),
                ('new_patients', models.PositiveIntegerField(default=0)),
                ('follow_up_patients', models.PositiveIntegerField(default=0)),
                ('unknown_patient_type_patients', models.PositiveIntegerField(default=0)),
                ('zakat_beneficiary_patients', models.PositiveIntegerField(default=0)),
                ('paying_patients', models.PositiveIntegerField(default=0)),
                ('unknown_payment_type_patients', models.PositiveIntegerField(default=0)),
                ('category_counts', models.JSONField(blank=True, default=dict, help_text='Flexible category breakdowns: by_department, by_diagnosis_category, by_age_band.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-clinic_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Report index page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DailyReportPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('report_date', models.DateField(unique=True)),
                ('summary_sentence', models.CharField(blank=True, help_text="The one AI-written summary sentence (CLAUDE.md invariant #4 exception) — a fixed-template restatement of this page's own aggregate figures. Blank if the AI call failed or was skipped; the numbers above still stand on their own.", max_length=400)),
                ('aggregate', models.ForeignKey(help_text='The aggregate this page renders. Figures are read live from here, never copied onto the page.', on_delete=django.db.models.deletion.PROTECT, related_name='report_page', to='pipeline.dailyaggregate')),
            ],
            options={
                'verbose_name': 'Daily report',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='IngestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_date', models.DateField(db_index=True)),
                ('parser_key', models.CharField(max_length=60)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.PositiveIntegerField(help_text='Number of de-identified visit rows this run produced for this date (0 for a duplicate no-op).')),
                ('content_hash', models.CharField(help_text='SHA-256 of the de-identified parsed rows for this date — a fingerprint, not the file. Identifies an exact-duplicate re-upload.', max_length=64)),
                ('status', models.CharField(choices=[('created', 'Created (first upload for this date)'), ('replaced', 'Replaced (corrected re-upload)'), ('duplicate', 'Duplicate (no-op, identical re-upload)')], max_length=20)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Who uploaded the export this run came from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_ingest_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='dailyaggregate',
            name='latest_ingest_run',
            field=models.ForeignKey(blank=True, help_text='The most recent ingest run that (re)computed this date.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pipeline.ingestrun'),
        ),
        migrations.CreateModel(
            name='DeidentifiedVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(db_index=True)),
                ('department', models.CharField(blank=True, max_length=80)),
                ('age_band', models.CharField(choices=[('0-4', '0–4'), ('5-12', '5–12'), ('13-17', '13–17'), ('18-40', '18–40'), ('41-60', '41–60'), ('61+', '61+'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other_unknown', 'Other / unknown')], default='other_unknown', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Coarse location (village / union council) — never a full street address.', max_length=120)),
                ('diagnosis_category', models.CharField(choices=[('hypertension', 'Hypertension'), ('diabetes', 'Diabetes'), ('respiratory_infection', 'Respiratory infection'), ('gastrointestinal', 'Gastrointestinal'), ('musculoskeletal', 'Musculoskeletal'), ('dermatological', 'Dermatological'), ('maternal_and_child_health', 'Maternal & child health'), ('cardiac', 'Cardiac'), ('infectious_disease', 'Infectious disease'), ('other', 'Other / unclassified')], default='other', max_length=40)),
                ('is_new_patient', models.BooleanField(blank=True, help_text='True = new patient, False = follow-up, null = not recorded in the source export.', null=True)),
                ('is_zakat_beneficiary', models.BooleanField(blank=True, help_text='True = Zakat beneficiary, False = paying patient, null = not recorded in the source export.', null=True)),
                ('ingest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='pipeline.ingestrun')),
            ],
            options={
                'indexes': [models.Index(fields=['visit_date'], name='pipeline_de_visit_d_bc88a4_idx')],
            },
        ),
    ]
