# Generated by Django 5.2.16 on 2026-07-22 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_grant_newsletter_draft_run_view_permission'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampUploadReportPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('camp_date', models.DateField(help_text='The date of the camp.', unique=True)),
                ('camp_title', models.CharField(help_text="The camp's title, as entered by the admin at upload time (e.g. 'Free Medical Camp — Union Council X').", max_length=200)),
                ('summary_sentence', models.CharField(blank=True, help_text="Optional free-text summary. Not AI-generated at publish time (see this model's docstring) — a maintainer may fill it in by hand.", max_length=400)),
            ],
            options={
                'verbose_name': 'Camp upload report',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='dailyaggregate',
            name='report_kind',
            field=models.CharField(choices=[('daily', 'Daily clinic activity'), ('camp', 'Medical camp')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='ingestrun',
            name='report_kind',
            field=models.CharField(choices=[('daily', 'Daily clinic activity'), ('camp', 'Medical camp')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyaggregate',
            name='clinic_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name='dailyaggregate',
            constraint=models.UniqueConstraint(fields=('clinic_date', 'report_kind'), name='pipeline_dailyaggregate_unique_date_kind'),
        ),
        migrations.AddField(
            model_name='campuploadreportpage',
            name='aggregate',
            field=models.ForeignKey(help_text="This camp's aggregate (report_kind='camp'). Figures are read live from here, never copied onto the page.", on_delete=django.db.models.deletion.PROTECT, related_name='camp_report_page', to='pipeline.dailyaggregate'),
        ),
    ]
