# Generated by Django 5.2.16 on 2026-07-22 16:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_grant_newsletter_draft_run_view_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional intro copy for the archive.'),
        ),
    ]
