# Generated by Django 5.2.16 on 2026-07-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_campuploadreportpage_dailyaggregate_report_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportpage',
            name='empty_columns_flag_approved',
            field=models.BooleanField(default=False, help_text="Check this once a person has reviewed the empty-columns flag above and it's ready for the public page. Never set automatically by the pipeline."),
        ),
        migrations.AddField(
            model_name='dailyreportpage',
            name='empty_columns_flag_draft',
            field=models.TextField(blank=True, help_text='AI-drafted note on which free-text columns were left blank today (Plan 11 Track B9) — same review gate as the free-text summary above.'),
        ),
        migrations.AddField(
            model_name='dailyreportpage',
            name='freetext_summary_approved',
            field=models.BooleanField(default=False, help_text="Check this once a person has reviewed (and, if needed, edited) the free-text summary above and it's ready for the public page. Never set automatically by the pipeline."),
        ),
        migrations.AddField(
            model_name='dailyreportpage',
            name='freetext_summary_draft',
            field=models.TextField(blank=True, help_text="AI-drafted summary of today's free-text clinical columns (Plan 11 Track B8). NOT shown on the public page until a person checks 'Free-text summary approved' below and (re)publishes this page. Regenerated on every (re-)ingest for this date."),
        ),
        migrations.AddField(
            model_name='deidentifiedvisit',
            name='clinical_notes',
            field=models.TextField(blank=True, default='', help_text="Doctor's/Nurse's/Dietitian's notes, whichever the source export carries for this visit, concatenated if more than one is present — see apps.pipeline.parser_tkc_daily_v1 for how these are combined."),
        ),
        migrations.AddField(
            model_name='deidentifiedvisit',
            name='diet_and_drug_compliance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deidentifiedvisit',
            name='investigation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deidentifiedvisit',
            name='plan_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deidentifiedvisit',
            name='prescribed_medicine',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deidentifiedvisit',
            name='presenting_complaints',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deidentifiedvisit',
            name='provisional_diagnosis_text',
            field=models.TextField(blank=True, default='', help_text='Raw free text, distinct from `diagnosis_category` above (a fixed keyword-mapped category derived from this same source column) — kept separately because B8/B9 need the actual text, not the category.'),
        ),
    ]
