# Generated by Django 5.2.16 on 2026-07-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_dailyreportpage_empty_columns_flag_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_site', models.CharField(choices=[('newsletter_prose', 'Newsletter prose (draft_newsletter_prose — currently unused)'), ('daily_summary', 'Daily report summary sentence'), ('monthly_newsletter', 'Monthly newsletter drafting')], max_length=30)),
                ('model', models.CharField(help_text='Anthropic model id, e.g. claude-sonnet-5.', max_length=60)),
                ('input_tokens', models.PositiveIntegerField()),
                ('output_tokens', models.PositiveIntegerField()),
                ('cost_usd', models.DecimalField(decimal_places=8, help_text='input_tokens/output_tokens x the published per-model rate at call time — see apps.pipeline.ai_pricing.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
