# Generated by Django 5.2.16 on 2026-07-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_grant_ai_call_log_view_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreportpage',
            name='empty_columns_flag_approved',
        ),
        migrations.RemoveField(
            model_name='dailyreportpage',
            name='empty_columns_flag_draft',
        ),
        migrations.RemoveField(
            model_name='dailyreportpage',
            name='freetext_summary_approved',
        ),
        migrations.RemoveField(
            model_name='dailyreportpage',
            name='freetext_summary_draft',
        ),
        migrations.AddField(
            model_name='dailyreportpage',
            name='empty_columns_flag',
            field=models.TextField(blank=True, help_text='AI-drafted note on which free-text columns were left blank today (Plan 11 Track B9). Blank if the AI call failed or was skipped.'),
        ),
        migrations.AddField(
            model_name='dailyreportpage',
            name='freetext_summary',
            field=models.TextField(blank=True, help_text="AI-drafted summary of today's free-text clinical columns (Plan 11 Track B8) — a fixed-template restatement of this date's already-collected free-text entries. Blank if the AI call failed or was skipped."),
        ),
    ]
