# Generated by Django 5.2.16 on 2026-07-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0009_dailyreportpage_freetext_summary_autopublish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deidentifiedvisit',
            name='age_band',
            field=models.CharField(choices=[('0-5', '0–5'), ('6-18', '6–18'), ('19-55', '19–55'), ('56+', '56+'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
