# Generated by Django 5.2.16 on 2026-07-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline", "0010_alter_deidentifiedvisit_age_band"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aicalllog",
            name="call_site",
            field=models.CharField(
                choices=[
                    (
                        "newsletter_prose",
                        "Newsletter prose (draft_newsletter_prose — currently unused)",
                    ),
                    ("daily_summary", "Daily report summary sentence"),
                    ("monthly_newsletter", "Monthly newsletter drafting"),
                    ("freetext_summary", "Free-text summary (B8)"),
                    ("empty_columns_flag", "Empty-columns flag (B9)"),
                ],
                max_length=30,
            ),
        ),
    ]
