# Generated by Django 5.2.16 on 2026-07-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0011_alter_aicalllog_call_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campuploadreportpage',
            name='aggregate',
        ),
        migrations.RemoveField(
            model_name='campuploadreportpage',
            name='page_ptr',
        ),
        migrations.RemoveConstraint(
            model_name='dailyaggregate',
            name='pipeline_dailyaggregate_unique_date_kind',
        ),
        migrations.RemoveField(
            model_name='dailyaggregate',
            name='report_kind',
        ),
        migrations.RemoveField(
            model_name='ingestrun',
            name='report_kind',
        ),
        migrations.AddConstraint(
            model_name='dailyaggregate',
            constraint=models.UniqueConstraint(fields=('clinic_date',), name='pipeline_dailyaggregate_unique_date'),
        ),
        migrations.DeleteModel(
            name='CampUploadReportPage',
        ),
    ]
