# Generated by Django 5.2.16 on 2026-07-23 20:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0012_remove_campuploadreportpage_aggregate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportindexpage',
            name='camp_reports_intro',
            field=wagtail.fields.RichTextField(blank=True, help_text="Optional intro copy for the 'Camp reports' section."),
        ),
        migrations.AddField(
            model_name='reportindexpage',
            name='daily_reports_intro',
            field=wagtail.fields.RichTextField(blank=True, help_text="Optional intro copy for the 'Daily reports' section."),
        ),
    ]
