# Generated by Django 5.2.16 on 2026-07-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0013_reportindexpage_camp_reports_intro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreportpage',
            name='freetext_summary',
        ),
        migrations.AddField(
            model_name='dailyreportpage',
            name='freetext_summary_children',
            field=models.TextField(blank=True, help_text='AI-drafted summary of today\'s free-text clinical columns for child patients (Plan 14; age bands 0-5 and 6-18, an approximation of "under 14" — see freetext.py\'s Plan 14 grounding note). Blank if the AI call failed, was skipped, or no child visits were recorded that day.'),
        ),
        migrations.AddField(
            model_name='dailyreportpage',
            name='freetext_summary_female_adults',
            field=models.TextField(blank=True, help_text="AI-drafted summary of today's free-text clinical columns for female adult patients (Plan 14). Blank if the AI call failed, was skipped, or no female adult visits were recorded that day."),
        ),
        migrations.AddField(
            model_name='dailyreportpage',
            name='freetext_summary_male_adults',
            field=models.TextField(blank=True, help_text="AI-drafted summary of today's free-text clinical columns for male adult patients (Plan 14). Blank if the AI call failed, was skipped, or no male adult visits were recorded that day."),
        ),
    ]
