# Generated by Django 5.2.16 on 2026-07-25
#
# Drops the ``newsletter_prose`` call-site choice together with the dead
# ``apps.pipeline.ai.draft_newsletter_prose`` that was its only writer (Plan
# 09 superseded it with ``draft_monthly_newsletter_body``; nothing in
# production ever called it, so no row should carry this value).
#
# Choices-only change: ``call_site`` stays a plain CharField and Django
# enforces ``choices`` in form/model validation, never as a DB constraint.
# Any historical row still holding "newsletter_prose" therefore keeps its
# value and stays readable — ``get_call_site_display()`` just falls back to
# the raw string instead of a label. Deliberately no data migration:
# rewriting or deleting audit rows would be worse than an unlabelled one.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline", "0016_create_clinic_dashboard_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aicalllog",
            name="call_site",
            field=models.CharField(
                choices=[
                    ("daily_summary", "Daily report summary sentence"),
                    ("monthly_newsletter", "Monthly newsletter drafting"),
                    ("freetext_summary", "Free-text summary (B8)"),
                    ("empty_columns_flag", "Empty-columns flag (B9)"),
                ],
                max_length=30,
            ),
        ),
    ]
