# Generated by Django 5.2.16 on 2026-08-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0018_remove_reportindexpage_camp_reports_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyaggregate',
            name='service_revenue',
            field=models.JSONField(blank=True, default=dict, help_text='Per-service revenue for this clinic-date, in whole PKR: {"consultation": {"regular": {"qty": 3, "amount": 750}, "zakat": {"qty": 4, "amount": 1000}, "unknown": {"qty": 0, "amount": 0}}, ...}. `qty` is the number of rows where that fee was non-zero (services delivered, not patients — Plan 16 D14). The `unknown` bucket holds money from rows whose Status is neither Zakat nor Regular (Plan 22 D3).'),
        ),
        migrations.AddField(
            model_name='deidentifiedvisit',
            name='consultation_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deidentifiedvisit',
            name='laboratory_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deidentifiedvisit',
            name='pharmacy_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deidentifiedvisit',
            name='registration_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deidentifiedvisit',
            name='ultrasound_fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
